spring.application.name=lab-manager

lab-manager.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.properties.hibernate.globally_quoted_identifiers_skip_column_definitions=true

jwt.expiration=${JWT_EXPIRATION:900000}
jwt.key=${JWT_KEY:qdk5!wYwZxD#nCNiyaJugRLgofs26!p8XBMjrzjrh=IorKWEAloVW&83d8mibZG1r4Vq9bSIvKKlekPxDUI0=Ud4PUN6WZwCs-6Ou!qd$YnVxZ-l$AWKEJuNTvS1LfB#rMFhV&-v5tSQw0RQdrN4Fu0exBmGUOKerNttU_tLxnvryT0$VjCuUh=ef5dca05_e_qXPC8mv#7Z=CXy8Hwsa70EUVnwaOcU-gHLtq4Dbk$vIdvU&3OmC&Hfd6uTs6ng_3a_PYCZUv4#Tn8D0&kA-IA$bfGiM_UnjM9zn#qJEPKOShNEZOriz9!9T7cBXZ5N3Z$T7#kVwTQV31Qv1S9J5I6e}
