services:
  mysql:
    image: mysql:8.4
    container_name: lab_manager_mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab_manager
      MYSQL_USER: ${DB_USERNAME:-admin}
      MYSQL_PASSWORD: ${DB_PASSWORD:-admin123}

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
