services:
  mysql:
    image: mysql:8.4
    container_name: lab_manager_mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab_manager
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/db/migration/V1__create_initial_schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_data:
